### ISSUE TITLE
Tag BoneScript v0.2.5 

### ISSUE THREAD

**Issue by fivdi** [jadonk/bonescript#109]
It would be nice if there was a tag for BoneScript v0.2.5. This would make it easier to find things in the future.

**Comment by jarvischung** [comment]
I can't use it on Beaglebone Green, right?

**Comment by jarvischung** [comment]
It's not support kernel 4.x.x for Beaglebone Green.

**Comment by adityapatadia** [comment]
Use OctalBoneScript.

**Comment by jadonk** [comment]
It is tagged.

**Comment by fivdi** [comment]
Yes, it looks like it was [tagged on Sep 17 2015](https://github.com/jadonk/bonescript/releases) shortly after this issues was created. I hadn't spotted that.
