### ISSUE TITLE
my.is_cape_universal not sufficient for 4.1 kernel

### ISSUE THREAD

**Issue by jadonk** [jadonk/bonescript#112]
For our default 4.1 kernel, we have pinmux helpers loaded without needing to load cape-universal. Instead of relying on cape-universal or trying to do a capemgr overlay, we should check the pins for the pinmux helper entries and keep that the priority.

It might be necessary to check on a per-pin basis and fall-back to using capemgr overlays for pins that don't have pinmux helper entries.

**Comment by akdbadoub** [comment]
did this got solved or should i down grade my kernel?

**Comment by jadonk** [comment]
I'd recommend trying 'sudo npm install -g bonescript@beta'.
