### ISSUE TITLE
pinMode fails, can't write /sys/kernel/debug/omap_mux/

### ISSUE THREAD

**Issue by lekamm** [jadonk/bonescript#117]
Hi,

I try to to very basic pinMode on my new beaglebone black updated with the latest debian image:
- Linux beaglebone 4.1.15-ti-rt-r43 #1 SMP PREEMPT RT Thu Jan 21 20:13:58 UTC 2016 armv7l GNU/Linux
- node: v0.10.41
- bonescript: 0.2.5

**Output in debug mode**

> var b = require('bonescript');
> debug: is_ocp() = undefined
> debug: Error reading undefined
> debug: is_cape_universal() = undefined
> debug: Using 3.2 kernel interface
> debug: index.js loaded
> undefined
> debug: Calling run()
> var led = "P9_14";
> undefined
> b.pinMode(led, b.OUTPUT);
> debug: pinMode(P9_14,out,,,);
> debug: Unable to configure mux for pin [object Object]: Error writing to /sys/kernel/debug/omap_mux/gpmc_a2: **Error: EACCES, permission denied '/sys/kernel/debug/omap_mux/gpmc_a2'**
> debug: getPinMode(P9_14);
> debug: getPinMode(P9_14): Error: ENOENT, no such file or directory '/sys/kernel/debug/omap_mux/gpmc_a2'
> info: **Error writing to /sys/kernel/debug/omap_mux/gpmc_a2**: Error: EACCES, permission denied '/sys/kernel/debug/omap_mux/gpmc_a2'
> false

Trying to write the file from the terminal using various methods failed too (sudo, sudo su, echo, tee etc ..)

Any idea why this is happening ?
Regards,
Cam

**Comment by jadonk** [comment]
For the 4.1 kernel, update to bonescript@beta. You can install with 'npm install -g bonescript@beta' as root user. The installed bonescript version should currently be 0.5.0-beta3.
