### ISSUE TITLE
Blank EEPROM before writing to it

### ISSUE THREAD

**Issue by koenkooi** [jadonk/bonescript#14]
I noticed some garbage data in the pinmux section of the cape I flashed with bonescript. It went away by doing cat /dev/zero > /sys/bus/i2c/blah/eeprom before running the flasher.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#12

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#41
