### ISSUE TITLE
Feature: stepper motors

### ISSUE THREAD

**Issue by troywweber7** [jadonk/bonescript#147]
Is there any plan/forks that offer firmata-like stepper motor support? If there were, then perhaps beaglebone-io could run steppers within Johnny-Five.

**Comment by jadonk** [comment]
Not currently. Best way would likely to do some dedicated PRU firmware and bind it to BoneScript. Perhaps we should extract the PRU firmware from Machinekit?

**Comment by troywweber7** [comment]
@jadonk I honestly haven't look at Machinekit yet. I will have to give it a look.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#40
