### ISSUE TITLE
recommended development and bonescript simulation on non-beaglebone platforms

### ISSUE THREAD

**Issue by troywweber7** [jadonk/bonescript#150]
This issue is a 2-part issue:

1. does bonescript have to always be developed on the beaglebone itself (this is clunky and difficult to support)?

2. does bonescript have a simulator mode similar to octalbonescript?

**Comment by troywweber7** [comment]
@jadonk makes sense, I look forward to seeing what the backend looks like! Should I close this now?

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#50
