### ISSUE TITLE
Make pin names case and punctuation not matter

### ISSUE THREAD

**Issue by jadonk** [jadonk/bonescript#153]
_ should be to be able to be replaced with a . or , or -

case should not matter

**Comment by scarecrow21** [comment]
Hi. I'd like to work on this. Can you guide me through this.

**Comment by jadonk** [comment]
fixed at https://github.com/jadonk/bonescript/commit/aa67a2aa27280cfdf607a9e5626a710eb91d2461 

@scarecrow21 wasn't sure how to guide you to doing the fix. Do you know how to do a github pull request? Do you know enough JavaScript to make the edits?
