### ISSUE TITLE
bizarre value parsing in attachInterrupt.intHandler

### ISSUE THREAD

**Issue by mvduin** [jadonk/bonescript#163]
The local `intHandler` function inside `attachInterrupt` contains:
```js
m.value = parseInt(Number(gpioInt[n].value), 2);
```

I was honestly surprised this even works at all since `gpioInt[n].value` is a Buffer here, and passing it to Number() makes no sense. Apparently however it just stringifies the buffer and then converts that to number. Of course passing a number to parseInt() also makes little sense, it will again stringify it and again convert it to a number.

I'd suggest changing it to `parseInt(gpioInt[n].value.toString(), 2)` to clarify what it's doing and avoid two pointless conversions.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#45
