### ISSUE TITLE
BeagleBone Blue support?

### ISSUE THREAD

**Issue by TheGreatJK** [jadonk/bonescript#177]
Are there plans to include support for the BeagleBone Blue? Or is it already available, and I'm missing something? I can't seem to find an entirely usable way to control the board's io in JavaScript... any leads?

**Comment by jadonk** [comment]
There's some base support there. I did an initial hack to add support for libroboticscape/libroboticscontrol, but it was changing too much. It is getting stable now, so I should be able to put it back in soon.

**Comment by jadonk** [comment]
btw, the pin names are in the form of https://github.com/jadonk/bonescript/blob/master/test/test-bone.js#L72

**Comment by jadonk** [comment]
Please test.
