### ISSUE TITLE
how to see winston.debug statements

### ISSUE THREAD

**Issue by anthonywebb** [jadonk/bonescript#46]
What is the best way to see the winston.debug statements in index.js? Is there a flag I pass in?  I assume they will show up in the console?  It would help while debugging to take a look at those.  Thanks.

**Comment by rwaldura** [comment]
How to trigger verbose logging output?
I pass DEBUG=1 and only see the few console.log() statements from the top of index.js.

$ DEBUG=1 node mybonescriptprogram.js
4:19:94-ti-r45
Using Mainline interface
