### ISSUE TITLE
Can't use 2 PWMs

### ISSUE THREAD

**Issue by daguej** [jadonk/bonescript#49]
If I try to use EHRPWM1A and EHRPWM1B:

```
b.pinMode('P9_14', b.OUTPUT);
b.pinMode('P9_16', b.OUTPUT);

b.analogWrite('P9_14', 0.5, 100);
b.analogWrite('P9_16', 0.5, 100);
```

...whichever is initialized second doesn't work.  If I look in /sys/devices/ocp.2,

```
# ls pwm*
pwm_test_P9_14.14:
driver  duty  modalias  period  polarity  power  run  subsystem  uevent

pwm_test_P9_16.15:
modalias  power  subsystem  uevent
```

**Comment by tovwiv** [comment]
any update on this? ran into this exact issue today

**Comment by adityapatadia** [comment]
May be you can try https://www.npmjs.com/package/octalbonescript

**Comment by NikolaMorena** [comment]
Workaround: use pins that are not connected with same EHRPWM module, e.g. P9_14 and P8_13

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#15
