### ISSUE TITLE
Using P9_15 kills the network connection

### ISSUE THREAD

**Issue by anthonywebb** [jadonk/bonescript#51]
Here is something really odd, using the latest bonescript from the repo, I can crash the network connection by trying to use pin P9_15.  Here is the sample code that will crash stuff:

``` javascript
var b = require('bonescript');
b.pinMode("P9_15", b.OUTPUT);
```

@jadonk to the rescue...

**Comment by jadonk** [comment]
@anthonywebb Sorry to miss the request to re-open. Are you seeing this issue with bonescript 0.5.0?

**Comment by jadonk** [comment]
@anthonywebb did you ever try with the latest bonescript?
