### ISSUE TITLE
FALLING edge interrupt not being installed properly

### ISSUE THREAD

**Issue by maxwellhadley** [jadonk/bonescript#76]
I'm using bone script 0.2.4, node.js v0.8.22 on a BBB.
uname -a gives:
Linux beaglebone 3.8.13 #1 SMP Thu Sep 12 10:27:06 CEST 2013 armv7l GNU/Linux

Using pin p8_12, when I attach an interrupt of type bonescript.FALLING, I actually get an interrupt of type bonescript.CHANGE. Attaching an interrupt of type bonescript.RISING works as expected.

What should happen:
Attaching an interrupt of type bonescript.FALLING should attach an interrupt which is triggered on the 1 -> 0 change of the input pin state only.

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#20
