### ISSUE TITLE
i2cscan returns empty data array

### ISSUE THREAD

**Issue by snidera** [jadonk/bonescript#77]
i2cscan is returning an empty array on '/dev/i2c-2', when I have a device connected at 0x20 & 0x21 (and can read/write to both via another script & i2cdetect -r 1 shows both)

Clean 9/4 image installed yesterday.  Tried both before & after updated to bonescript 0.2.4

I've modified the 'test-i2c' from github as follows:

var b = require('bonescript');
var port = '/dev/i2c-2';

b.i2cOpen(port);
b.i2cScan(port, onScan);

function onScan(err, data) {
    console.log('scan = ' + JSON.stringify(arguments));
}

If I run it using '/dev/i2c-0', I get the same output as 'test-i2c'  (data=[52,80])  

scan = {"0":{"err":null,"data":[52,80],"event":"callback"}}
scan = {"0":{"event":"return","return":[
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,52,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
80,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1]}}

If I run on /dev/i2c-1 or /dev/i2c-2, I get an empty array in data.

scan = {"0":{"err":null,"data":[],"event":"callback"}}
scan = {"0":{"event":"return","return":[
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1]}}

What am I doing wrong?

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#21
