### ISSUE TITLE
Failed to find devicetree fragment bspwm

### ISSUE THREAD

**Issue by coreindustries** [jadonk/bonescript#78]
Hi.

Thanks for working on bonescript. It's a great asset.

I'm running a BeagleBone black, with Ubuntu 13.10 from https://rcn-ee.net/deb/rootfs/saucy/ubuntu-13.10-console-armhf-2014-02-16.tar.xz

```
root: uname -a
Linux arm 3.8.13-bone41 #1 SMP Sat Mar 1 04:45:31 UTC 2014 armv7l armv7l armv7l GNU/Linux
```

And getting the following error when I try to use PWM:

**error: Failed to find devicetree fragment: bspwm_P9_14_e**

info:  0: 54:PF---
 1: 55:PF---
 2: 56:PF---
 3: 57:PF---
 4: ff:P-O-L Bone-LT-eMMC-2G,00A0,Texas Instrument,BB-BONE-EMMC-2G
 5: ff:P-O-L Bone-Black-HDMI,00A0,Texas Instrument,BB-BONELT-HDMI
 7: ff:P-O-L Override Board Name,00A0,Override Manuf,bspm_P9_14_f
 8: ff:P-O-L Override Board Name,00A0,Override Manuf,am33xx_pwm

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#22
