### ISSUE TITLE
serialParsers problem

### ISSUE THREAD

**Issue by docwelch** [jadonk/bonescript#85]
I am trying to run the test-serial.js example. When I start it, I get the following error:
debugger listening on port 15454

/var/lib/cloud9/SerialTest.js:4
var options = { baudrate: 115200, parser: b.serialParsers.readline('\n') };
                                                                                           ^
TypeError: Cannot call method 'readline' of undefined
    at Object.<anonymous> (/var/lib/cloud9/SerialTest.js:4:59)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain [as _onTimeout](module.js:497:10)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

[Process stopped]

If I change the var options line to:
   var options= {baudrate: 115200}; //leave out the parser
everything works. I can actually send and get back data (though it is obviously not parsed correctly). Based on the fact it works without the "parser:b.serialParsers.readline('\n'), I think I have everything installed correctly (though I am a newbie to this so anything is possible). 

I should mention I am running the Debian distribution (2014-04-23) and BoneScript 0.2.4

Thanks in advance.

**Comment by frank5192035** [comment]
Hi:
  I made UART1 and UART4 mutual communication with each other. But I found the received data always go throught first call back function "onUART4" as following code. I also try to change the "b.serialOpen(UART4, options, onUART4);" after the line "b.serialOpen(UART1, options, onUART1);".
The result became it always called the onUART1 function. It behave like only one call back function can work. I am not sure what's the problem?

The code I wrote:

var b = require('bonescript');

var UART1 = '/dev/ttyO1';
var UART4 = '/dev/ttyO4';
var options = {
    // baudrate: 9600, 
    // buffersize: 1000
    // parser: b.serialport.parsers.readline("\n")
    // parser: b.parsers
}

b.serialOpen(UART4, options, onUART4);
setTimeout(Sending4, 1200);
b.serialOpen(UART1, options, onUART1);
setTimeout(Sending1, 1000);

function onUART1(x) {
    if (x.err) {
        console.log('***ERROR*** ' + JSON.stringify(x));
    }
    if (x.event == 'open') {
        console.log('*** UART1 OPENED ***');
    }
    if (x.event == 'data') {
        // console.log('UART1 Rx: ' + String(x.data));
        console.log('UART1 Rx: ' + x.data);
    }
}

function onUART4(x) {
    if (x.err) {
        console.log('***ERROR*** ' + JSON.stringify(x));
    }
    if (x.event == 'open') {
        console.log('*** UART4 OPENED ***');
    }
    if (x.event == 'data') {
        console.log('UART4 Rx: ' + String(x.data));
    }
}


function Sending1() {
    b.serialWrite(UART1, 'aaa');
}
function Sending4() {
    b.serialWrite(UART4, 'bbb');
}


===>>> The execution result:
[root@ /var/lib/cloud9/javascripts]# node UART.js 
*** UART4 OPENED ***
*** UART1 OPENED ***
UART4 Rx: aaa
UART4 Rx: bbb

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#25
