### ISSUE TITLE
Available digital inputs

### ISSUE THREAD

**Issue by pmcalabrese** [jadonk/bonescript#87]
Hello,
Because some digital inputs are set to high (P8_7 P8_9) and some others (like P8_23 P8_25 P8_27) cannot be red from bonescript... i would like to know if there is a list of available digital inputs for the BBB.

Thank you in advance

(BeagleBone Black rev 000B with Amstrong running BoneScript 0.2.2)

**Comment by jadonk** [comment]
http://beagleboard.org/support/bone101/#headers should be a good resource as well.

**Comment by raspiest** [comment]
thanks
