### ISSUE TITLE
disable pwm output

### ISSUE THREAD

**Issue by colinbes** [jadonk/bonescript#88]
I am running bonescript 0.2.4 on latest debian image on bbb.

I have two PWM outputs; P9_22 and P9_42

After a period I need to shutdown pwm outputs (take them to low). As their is no function exposed to write a zero (0) to 'run' I have used recommendation to write a zero to dutycycle in analogWrite, for simple code example see:

```
var b = require('bonescript');
var pulseOutput = "P9_42";
b.analogWrite(pulseOutput, 0.5, 2000)
setTimeout(function(){
    b.analogWrite(pulseOutput, 0)
    }, 10000);
```

P9_42 output pin goes low as expected, but P9_22 doesn't - it has a 10nS spike every 500uS.

Manually writing zero to `echo 0 > /sys/devices/ocp.3/bs_pwm_test_P9_22.16/run` does work.

Any ideas/suggestions?

Would it be possible to expose disable/enable function in upcoming release?

Thanks
Colin

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#26
