### ISSUE TITLE
Using I2C functions

### ISSUE THREAD

**Issue by colinbes** [jadonk/bonescript#90]
Maybe I am misunderstanding correct usage of I2C functions provided by bonescript but from what I understand, the correct usage is along the lines of

```
b.i2cOpen(PORT, PWR_CHIP);
b.i2cReadBytes(PORT, STATUS, 1, function(data){...})
```

I assume the thinking is that the ReadBytes is always preceded by the i2cOpen function within the same function scope. If the i2cOpen function was, for example, in static part of code, and the ReadBytes was in a function then you could end up with wrong results.

Example.

```
i2cOpen('/dev/i2c-1', 0x20);

function func1() {
  i2cReadBytes .....
}
```

In this case if any other function anywhere called i2cOpen and then you called func1() you'd be reading bytes of the last i2cOpen function.

Is there a way to use these functions similar to the way it is used in i2c which is basis for bonescript i2c functions? Where method returned by i2cOpen is used as 'parent' (sorry, can't think of right word to use) to ReadBytes call?

Just looking for direction, thanks

**Comment by jadonk** [comment]
This issue was moved to beagleboard/bonescript#28
