### ISSUE TITLE
Name of mode7 for pin P8_7

### ISSUE THREAD

**Issue by btittelbach** [jadonk/bonescript#92]
Hi,

in bone.js entry "TIMER4" aka P8_7:
mode7 is named "mmc1_sdcd" but I believe that should be "gpio2_2" instead.

(hewball on #beagle@irc.freenode.net originally noticed that.)

**Comment by jadonk** [comment]
The name was reported by the old 3.2 kernel for mode 7 due to its use on the pre-defined MMC1 interface. I guess this is largely legacy now, but I'm not so sure it is all that helpful to fix either.

**Comment by btittelbach** [comment]
I think it would be very helpful if you consider that the bone.js script was and for many people still is an easy to read and accurate documentation of the beaglebone pins.
Also, some helper utilities (inkluding one of my own) use bone.js to display interactive documentation for the beaglebone.

**Comment by jadonk** [comment]
Since this is the main GPIO function, to act as MMC1 card detect, I'm not sure I can simply remove that name.  Would adding it after a slash (/) work?

**Comment by jadonk** [comment]
Adjusted to meet this request per https://github.com/jadonk/bonescript/commit/034e55e389bab6fbad7bfe857c5a2f2e81ede347.
