### ISSUE TITLE
Default webpage after update of bonescript is broken.

### ISSUE THREAD

**Issue by robertm1771** [jadonk/bonescript#95]
I follow the instructions for updating bonescript from git page and after update and reboot accessing default web page gives a "Cannot GET /" message.

Example point chrome at "192.168.7.2" gives the message in web page "Cannot GET /"

I can still access the cloud9  environment just not the default web page.

**Comment by jadonk** [comment]
It is indeed served up by bonescript. There was a change to some of the debian packages that made this transition difficult for people at this time.
